In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./CORESTICKM159SFRBATL.csv")
df

           DATE  CORESTICKM159SFRBATL
0    1968-01-01              3.651861
1    1968-02-01              3.673819
2    1968-03-01              4.142164
3    1968-04-01              4.155828
4    1968-05-01              4.088245
..          ...                   ...
672  2024-01-01              4.603922
673  2024-02-01              4.403102
674  2024-03-01              4.509212
675  2024-04-01              4.412395
676  2024-05-01              4.302023

[677 rows x 2 columns]

In [3]:
df2 = pd.read_csv("./T5YIE.csv")
df2

            DATE T5YIE
0     2014-08-29  1.76
1     2014-09-01     .
2     2014-09-02  1.76
3     2014-09-03  1.77
4     2014-09-04  1.76
...          ...   ...
2564  2024-06-27  2.22
2565  2024-06-28  2.24
2566  2024-07-01  2.29
2567  2024-07-02  2.26
2568  2024-07-03  2.23

[2569 rows x 2 columns]