In [1]:
import pandas as pd

In [5]:
df_monthly = pd.read_csv("./Monthly.csv")
df_monthly

,DATE,PPIACO_NBD19130101,CPIAUCSL_NBD19470101,PCE_NBD19590101,FRBATLWGT3MMAUMHWGO_NBD19970301,IR_NBD19970301,M2SL_NBD20010101
0,2015-01-01,1586.77686,1092.86313,3942.07775,66.66667,126.0,236.44110
1,2015-02-01,1579.33884,1095.63315,3958.37961,66.66667,125.5,238.57548
2,2015-03-01,1582.64463,1098.58473,3977.81771,71.11111,125.3,238.83273
3,2015-04-01,1577.68595,1099.72998,3988.59850,73.33333,125.1,239.62859
4,2015-05-01,1598.34711,1103.35661,4010.25809,73.33333,126.5,240.25564
...,...,...,...,...,...,...,...
108,2024-01-01,2076.90909,1441.73650,6216.26919,111.11111,139.4,417.11518
109,2024-02-01,2106.72727,1448.10987,6251.55178,111.11111,139.7,416.99861
110,2024-03-01,2108.39669,1453.58473,6293.27017,104.44444,140.5,418.87775
111,2024-04-01,2125.23140,1458.13315,6301.82947,.,141.8,419.44249
112,2024-05-01,2107.19835,1458.21695,6317.47795,.,141.2,421.31559

In [6]:
df_daily = pd.read_csv("./Daily.csv")
df_daily

            DATE DCOILBRENTEU_NBD20001229
0     2015-01-02                245.26129
1     2015-01-05                226.21789
2     2015-01-06                221.96634
3     2015-01-07                217.27192
4     2015-01-08                218.91054
...          ...                      ...
2472  2024-06-25                384.45527
2473  2024-06-26                379.80514
2474  2024-06-27                385.29672
2475  2024-06-28                386.44818
2476  2024-07-01                383.39238

[2477 rows x 2 columns]

In [8]:
df_annually = pd.read_csv("./Quarterly.csv")
df_annually

          DATE  GDPDEF_NBD19970101  ECIALLCIV_NBD20010101
0   2015-01-01           140.19413              145.92680
1   2015-04-01           140.99964              146.16293
2   2015-07-01           141.37342              147.10744
3   2015-10-01           141.37052              147.93388
4   2016-01-01           141.24737              148.76033
5   2016-04-01           142.20790              149.58678
6   2016-07-01           142.57153              150.41322
7   2016-10-01           143.26114              151.23967
8   2017-01-01           143.99131              152.18418
9   2017-04-01           144.36798              153.12869
10  2017-07-01           145.10974              154.19126
11  2017-10-01           146.00217              155.13577
12  2018-01-01           146.93082              156.31641
13  2018-04-01           147.96958              157.37898
14  2018-07-01           148.60848              158.55962
15  2018-10-01           149.24882              159.74026
16  2019-01-01           149.76458              160.68477
17  2019-04-01           150.50779              161.74734
18  2019-07-01           150.97573              162.92798
19  2019-10-01           151.45382              163.99055
20  2020-01-01           152.17240              165.28926
21  2020-04-01           151.55958              166.11570
22  2020-07-01           152.89823              166.82409
23  2020-10-01           153.96595              168.24085
24  2021-01-01           155.98406              169.65762
25  2021-04-01           158.35567              170.83825
26  2021-07-01           160.69540              172.96340
27  2021-10-01           163.48859              174.85242
28  2022-01-01           166.80188              177.21370
29  2022-04-01           170.47591              179.57497
30  2022-07-01           172.34625              181.70012
31  2022-10-01           173.98479              183.70720
32  2023-01-01           175.67693              185.83235
33  2023-04-01           176.40855              187.72137
34  2023-07-01           177.85150              189.61039
35  2023-10-01           178.58892              191.38135
36  2024-01-01           179.95219              193.62456

In [9]:
df_daily.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2477 entries, 0 to 2476
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATE                      2477 non-null   object
 1   DCOILBRENTEU_NBD20001229  2477 non-null   object
dtypes: object(2)
memory usage: 38.8+ KB

In [10]:
df_annually.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   DATE                   37 non-null     object
 1   GDPDEF_NBD19970101     37 non-null     float64
 2   ECIALLCIV_NBD20010101  37 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1020.0+ bytes

KeyError: 'Price'